[default]
src = "src/contracts"
out = "build/artifacts"
libs = ["node_modules"]
optimizer = true
optimizer_runs = 800
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@kreskolabs/=node_modules/@kreskolabs/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@uniswap/=node_modules/@uniswap/',
    'contracts/=node_modules/@uniswap/lib/contracts/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
    'helpers/=src/contracts/diamond/helpers/',
    'prettier-plugin-solidity/=node_modules/prettier-plugin-solidity/',
]
