[default]
src = "src/contracts"
out = "forge/artifacts"
libs = ["node_modules", "lib"]
extra_output = [
    'abi',
    'evm.bytecode.object',
    'evm.deployedBytecode.object',
    'evm.methodIdentifiers',
    'evm.gasEstimates',
]

optimizer = true
optimizer_runs = 200
cache = true
cache_folder = "forge/cache"

[default.optimizer_details]
yul = true

[default.optimizer_details.yulDetails]
stackAllocation = true
