name: Install cached packages
on: [push]
jobs:
    install-with-cache:
        name: Create new build on EAS
        runs-on: ubuntu-latest
        steps:
            - name: Setup repo
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org
                  scope: kreskolabs
            - name: Reconfigure git to use HTTP authentication
              run: git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf ssh://git@github.com/
            - name: Update NPM
              run: npm install npm@latest --location=global
            - name: Install dependencies
              run: npm i --force
